Repository brazil-data-cube/cube-builder, pull requests merged in 2020-10, with the labels that each got.

#90 change structure - files and folders
  INSTALL.rst
  USING.rst
  cube_builder/__init__.py
  cube_builder/blueprint.py
  cube_builder/business.py
  cube_builder/celery/tasks.py
  cube_builder/cli.py
  cube_builder/config.py
  cube_builder/controller.py
  cube_builder/forms.py
  cube_builder/maestro.py
  cube_builder/parsers.py
  cube_builder/utils/__init__.py
  cube_builder/utils/image.py
  cube_builder/utils/package.py
  cube_builder/utils/processing.py
  cube_builder/views.py
  setup.py
Labels: enhancement

#91 add endpoints to get infos by cube (status, tasks)
  cube_builder/__init__.py
  cube_builder/celery/utils.py
  cube_builder/controller.py
  cube_builder/forms.py
  cube_builder/utils/serializer.py
  cube_builder/views.py
Labels: enhancement

#92 refactoring the script for building the timeline
  cube_builder/controller.py
  cube_builder/forms.py
  cube_builder/maestro.py
  cube_builder/utils/timeline.py
  cube_builder/views.py
Labels: enhancement

#93 add endpoint to list items by cube
  cube_builder/controller.py
  cube_builder/forms.py
  cube_builder/views.py
Labels: enhancement

#96 Cube Builder Improvements - Add stac url parameter and fix dependency error
  cube_builder/cli.py
  cube_builder/forms.py
  cube_builder/maestro.py
  setup.py
Labels: bug, enhancement

#99 Fix minor imports and remove useless code
  cube_builder/controller.py
  cube_builder/views.py
Labels: bug

#101 Add grid CRUD to use in cube-builder-app
  cube_builder/controller.py
  cube_builder/utils/timeline.py
  cube_builder/views.py
Labels: bug, enhancement

#104 add shape params
  cube_builder/controller.py
  cube_builder/forms.py
  cube_builder/maestro.py
  cube_builder/utils/processing.py
Labels: bug, enhancement
