Repository brazil-data-cube/cube-builder, pull requests merged in 2021-03, with the labels that each got.

#144 Generate nodata dataset when no scenes found in period (close #143)
  cube_builder/celery/tasks.py
  cube_builder/maestro.py
  cube_builder/utils/image.py
Labels: enhancement

#145 Upgrade to bdc-catalog 0.8; Add configure-db.sh
  cube_builder/cli.py
  deploy/configure-db.sh
  setup.py
Labels: bug, documentation

#146 Review prepare blend priority - set tasks queues
  cube_builder/celery/tasks.py
  cube_builder/cli.py
  cube_builder/config.py
  cube_builder/utils/package.py
  docker-compose.yml
Labels: enhancement

#147 Add authentication using BDC-Auth. Close #122
  cube_builder/config.py
  cube_builder/views.py
  setup.py
Labels: enhancement

#148 Add initial support to match histogram
  cube_builder/celery/tasks.py
  cube_builder/cli.py
  cube_builder/forms.py
  cube_builder/utils/image.py
  setup.py
Labels: enhancement

#149 Review Dockerfile and add .drone.yml
  .drone.yml
  Dockerfile
  MANIFEST.in
  docker-compose.yml
Labels: enhancement

#151 Review block size in datacubes generation
  cube_builder/celery/tasks.py
  cube_builder/controller.py
  cube_builder/forms.py
  cube_builder/utils/image.py
  cube_builder/utils/processing.py
Labels: bug

#152 list running and pending tasks in rabbitMQ
  cube_builder/celery/utils.py
  cube_builder/config.py
  cube_builder/views.py
  setup.py
Labels: enhancement

#153 Fix tests and docker-registry
  .drone.yml
  cube_builder/alembic/f639d83487b6_v0_4_0.py
  cube_builder/celery/__init__.py
  cube_builder/celery/tasks.py
  cube_builder/celery/utils.py
  cube_builder/celery/worker.py
  cube_builder/controller.py
  cube_builder/maestro.py
  cube_builder/models/activity.py
  cube_builder/utils/image.py
  cube_builder/utils/index_generator.py
  cube_builder/utils/processing.py
  cube_builder/utils/serializer.py
  cube_builder/utils/timeline.py
  cube_builder/views.py
  docs/sphinx/conf.py
  run-tests.sh
  setup.py
  tests/test_timeline.py
Labels: bug, test

#154 Add custom cloud masking
  cube_builder/alembic/b160749a148e_add_cube_parameters.py
  cube_builder/celery/tasks.py
  cube_builder/cli.py
  cube_builder/config.py
  cube_builder/controller.py
  cube_builder/forms.py
  cube_builder/maestro.py
  cube_builder/models/__init__.py
  cube_builder/models/activity.py
  cube_builder/models/cube_parameters.py
  cube_builder/utils/processing.py
Labels: enhancement

#156 Add support to use saturation band (radsat) to compose data cubes
  cube_builder/celery/tasks.py
  cube_builder/cli.py
  cube_builder/maestro.py
  cube_builder/models/cube_parameters.py
  cube_builder/utils/image.py
  cube_builder/utils/index_generator.py
  cube_builder/utils/processing.py
Labels: enhancement

#158 Adapt stac search to work with any stac 0.9+ (close #157)
  CHANGES.rst
  cube_builder/config.py
  cube_builder/maestro.py
  cube_builder/version.py
  setup.py
Labels: bug

#159 Merge 0.4.2 with master
  CHANGES.rst
  cube_builder/config.py
  cube_builder/maestro.py
  setup.py
Labels: release

#161 Create SPEC API
  MANIFEST.in
  cube_builder/__init__.py
  cube_builder/config.py
  cube_builder/spec/openapi.yaml
  setup.py
Labels: documentation

#160 Prepare to release 0.6.0
  CHANGES.rst
  INSTALL.rst
  cube_builder/utils/processing.py
Labels: documentation

#162 Minor fixes to release 0.6.0
  cube_builder/celery/__init__.py
  cube_builder/celery/tasks.py
  cube_builder/controller.py
  cube_builder/forms.py
  cube_builder/maestro.py
  cube_builder/utils/processing.py
  deploy/configure-db.sh
Labels: enhancement
